baseURL = "https://rowenjennings.netlify.app/"
title = "Rowen Jennings"
theme = "PaperMod"

# Theme configuration
[params]
env = "production"
author = "<Rowen Jennings>"
description = "Portfolio of past work, goals, and contact information"
keywords = ["Blog", "Portfolio", "PaperMod"]
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableScrollToTop = false

[params.label]
text = "Home"
icon = "/profile.png"
iconHeight = 24

[params.profileMode]
enabled = true
title = "Rowen Jennings"
subtitle = "They/Them"
imageUrl = "profile.png"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "tags"
url = "/tags/"

[[params.profileMode.buttons]]
name = "puppies"
url = "https://google.com/search?tbm=isch&q=puppies"

[[params.socialIcons]]
name = "email"
url = "https://instagram.com/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/jenningsj"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30

[[menu.main]]
identifier = "skills"
name = "Skills"
url = "https://google.com/search?tbm=isch&q=cute%20puppies"
weight = 20
